### ISSUE TITLE
How to really delete a softDeletable entity?

### ISSUE THREAD

**Issue by pfleu** [KnpLabs/DoctrineBehaviors#294]
Hi, I've been searching for a while but couldn't find a solution.
Is there a way (from a controller) to actually remove a softDeletable entity from the database?
Am I missing an existing feature?
Thanks.

**Comment by nifr** [comment]
Quick 'n dirty:

```
$entityManager = $this->getDoctrine()->getManager('default');
$eventManager = $entityManager->getEventManager();

// remove the softdeletable subscriber
$subscriber = $this->get('knp.doctrine_behaviors.softdeletable_subscriber');
$eventManager->removeEventListener($subscriber->getSubscribedEvents(), $subscriber);

// remove entity while the subscriber is removed
$entityManager->remove($entity);
$entityManager->flush();

// add back the subscriber
$eventManager->addEventSubscriber($subscriber);
```

**Comment by pfleu** [comment]
Thank you so much for your quick answer! This is just what I needed!

**Comment by pfleu** [comment]
@nifr I got the error "you have requested a non-existent service". After a quick search, I found the service in orm-services.yml and had to set "public: true" in order to get your solution to work. But this change will be lost after running composer, right? Can I make this change in a custom file somewhere else in my app so it's not lost after a composer update?

**Comment by nifr** [comment]
2 possible solutions:

1) define your controller itself as a service and inject the subscriber-service explicitly 
2) create a factory-service that would return the subscriber service and call that one in your controller

**Comment by migmolrod** [comment]
Maybe you can just overwrite the subscriber in your own services.yml? Haven't tried it myself to see if it works, but I'll probably need to test it very soon, since I'll need to completely disable that same filter/subscriber in my backend (so administrators can check out which entities are "soft-deleted", you know)

```yaml
# app/config/services.yml
services:
    knp.doctrine_behaviors.softdeletable_subscriber:
        class:   "%knp.doctrine_behaviors.softdeletable_subscriber.class%"
        public:  false
        arguments:
            - "@knp.doctrine_behaviors.reflection.class_analyzer"
            - "%knp.doctrine_behaviors.reflection.is_recursive%"
            - "%knp.doctrine_behaviors.softdeletable_subscriber.softdeletable_trait%"
        tags:
            - { name: doctrine.event_subscriber }
```
