### ISSUE TITLE
New version using symplify/package-builder ^8.0

### ISSUE THREAD

**Issue by I-Valchev** [KnpLabs/DoctrineBehaviors#575]
I'm having trouble updating [bolt/core](https://github.com/bolt/core) to use ecs ^8, because of incompatible versions with doctrine behaviors. But I see you've already updated to `symplify/package-builder ^8.0` on master.

Can you tag a new release so that this issue is resolved for people? :) Thanks

**Comment by TomasVotruba** [comment]
I'm not sure it's tested yet :/

Could you confirm how the DoctrineBehaviors dev-master version works?

**Comment by I-Valchev** [comment]
I'll check!

**Comment by I-Valchev** [comment]
```
!!
!!  In DefinitionErrorExceptionPass.php line 54:
!!
!!    Cannot autowire service "Knp\DoctrineBehaviors\EventSubscriber\HashidableEv
!!    entSubscriber": argument "$hashids" of method "__construct()" references cl
!!    ass "Roukmoute\HashidsBundle\Hashids" but no such service exists. Try chang
!!    ing the type-hint to "Hashids\HashidsInterface" instead.
!!
!!
!!
```

Does this make any sense to you? :-)

**Comment by TomasVotruba** [comment]
That was fixed here: https://github.com/KnpLabs/DoctrineBehaviors/pull/572

Just merged. Could you retry in 2-3 mins, when packagist gets the memo?

**Comment by I-Valchev** [comment]
Doesn't quite work, it seems...

```
Cannot autowire argument $content of "Bolt\Controller\Backend\ContentEditController::edit()": it references class "Bolt\Entity\Content" but no such service exists.
```

Content is an entity, explicitly excluded as a service, which was fine so far. Could this be related?

**Comment by TomasVotruba** [comment]
Not sure. I have no idea how this could be related, as Symfony configs can be autowired only in it's own scope.
I'd try removing cache and check the configs with bolt controller registration.

**Comment by I-Valchev** [comment]
OK that's very strange. I get no such issues, only when I set simplify to ^8 and doctrine-behaviors to dev-master. 🤔

**Comment by TomasVotruba** [comment]
How did you fix previous error?

**Comment by I-Valchev** [comment]
`DefinitionErrorExceptionPass.php` issue I waited and got the changes from the PR you merged in. Autowire thing does away if I revert back to simplify 7 and latest stable doctrine-behaviors.

**Comment by TomasVotruba** [comment]
> Autowire thing goes away if I revert back to simplify 7 and latest stable doctrine-behaviors.

That's not good :/ 
Last idea is to check `bundles.php`, sometimes symfony/flex adds undesired bundles.

If that doesn't help, we'd need reproducible repository on Github. This needs to be fixed before release

**Comment by I-Valchev** [comment]
I don't see anything wrong with the `bundles.php` :/

https://github.com/bolt/core/pull/1513
here is an example of it happening.

To reproduce:
grab that branch and install, then run `make db-reset` and login on the backend (default user/password is `admin` `admin%1`) and go to edit any page.

**Comment by TomasVotruba** [comment]
That's seems to hard, I can't invest that much time. 
Any unit test? Failing Githbu Action error would be the best

**Comment by I-Valchev** [comment]
I don't think the failing tests will be of much help... tests are checking what's on the page, but obviously that doesn't work as the issue is at controller level.

Maybe this will help:
![content-autowire-error](https://user-images.githubusercontent.com/7093518/85139170-54e47500-b244-11ea-824c-3dbb0b5da688.png)

**Comment by tsdevelopment** [comment]
Hi, sorry to interrupt you. But I think the error doesn't have to do anything with this package. I installed your branch and found the following in your ` app/config/services.yaml` file:

```yaml
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Bolt\:
        resource: '../src/*'
        exclude: '../src/{Entity,Exception,Migrations,Kernel.php}'
```
You exclude the ` Entity` directory. But in your edit function you want to autoload the `Content` Service:

```php
/**
     * @Route("/edit/{id}", name="bolt_content_edit", methods={"GET"}, requirements={"id": "\d+"})
     */
    public function edit(Request $request, Content $content): Response
    {
        [...]
    }
``` 
Remove `Entity` from `service.yaml` and the service will be available:

```yaml
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Bolt\:
        resource: '../src/*'
        exclude: '../src/{Exception,Migrations,Kernel.php}'
```

After that I run into another error. But it's not related to this package!
